### ISSUE TITLE
npm ERR! missing script: dev

### ISSUE THREAD

**Issue by chenwei19940207** [weacast/weacast#16]
This is now what in file "weacast/package.json". It seems there is no dev in scripts. The cmd gives me **npm ERR! missing script: dev** when I run npm run dev in weacast folder.
```
{
  "name": "weacast",
  "private": true,
  "scripts": {
    "install": "lerna bootstrap",
    "lint": "lerna run lint",
    "test": "nyc lerna run test"
  },
  "devDependencies": {
    "nyc": "^15.1.0",
    "lerna": "^4.0.0"
  }
}

**debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\chenw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v16.13.1
4 verbose stack Error: missing script: dev
4 verbose stack     at run (C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:382:12
4 verbose stack     at C:\Users\chenw\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
5 verbose cwd D:\project\weacast\weacast
6 verbose Windows_NT 10.0.22000
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chenw\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 verbose node v16.13.1
9 verbose npm  v6.14.16
10 error missing script: dev
11 verbose exit [ 1, true ]
```

**Comment by claustres** [comment]
Hi, I've just added a notice on the README. This repo is actually a new Weacast monorepo with all packages that will be published to the @weacast npm organization, which is a work in progress.

It was previously the repository of the weacast demo application you can now find here: https://github.com/weacast/weacast-app. Docs will be updated soon accordingly, sorry for the inconvenience.

**Comment by chenwei19940207** [comment]
> Thanks for your contributing and the reply @claustres, good work!

**Comment by chenwei19940207** [comment]
> I suggest not to use the master branch of the demo app now, which should not work anymore with previous weacast repos, you can use a tag if you'd really like to pull the demo app repo, otherwise rely on released docker images.

Oh no! I've been solved a thousand problems when set the development environment and finally been here.  Anyway thanks though!

**Comment by claustres** [comment]
@chenwei19940207 No worry, not much change in the documented environment setup, you should simply clone the demo app repo using the latest tag instead of this one and this sould work.
