### ISSUE TITLE
docker-compose - first attempt

### ISSUE THREAD

**Issue by jemacchi** [weacast/weacast#22]
### Steps to reproduce
Cloned repo and tried to use the instructions from here  https://weacast.github.io/weacast/guides/basics.html#installing
Just simply run the docker-compose commands (so avoid any source installation), and have a quick demo on the app.

### Expected behavior
Should start the server and mongo docker images and work (based on the doc)

### Actual behavior
The API docker container is showing this error:

```
>> docker logs 88d

> @weacast/api@2.1.3 prod
> cross-env NODE_ENV=production node src/main.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
info: Logger configured
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
(node:25) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
info: Initializing weacast-gfs plugin
info: Initializing gfs-world forecast
info: Installing forecast update on gfs-world with interval (s) 900
error: Can not find service 'api/arpege-europe/u-wind'
info: Configuring HTTP server at port 8081
info: Server started listening
/opt/weacast-api/node_modules/@kalisio/feathers-distributed/lib/index.js:292
  if (app.distributionOptions.publishEvents && serviceDescriptor.events.length && !service[EVENT_LISTENER_KEY]) {
                                                                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at publishService (/opt/weacast-api/node_modules/@kalisio/feathers-distributed/lib/index.js:292:73)
    at /opt/weacast-api/node_modules/@kalisio/feathers-distributed/lib/index.js:316:7
    at Array.forEach (<anonymous>)
    at Timeout._onTimeout (/opt/weacast-api/node_modules/@kalisio/feathers-distributed/lib/index.js:315:46)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.19.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.19.2>
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 

````

### System configuration

Ubuntu 22.04.1 LTS
Docker Compose version v2.5.1
Docker version 20.10.19, build d85ef84

**Comment by claustres** [comment]
Hi @jemacchi and thanks for feedback, as we recently moved to a monorepo project and also moved the demo application in a new repository some changes remain to be done in documentation. This section of the documentation actually refers to docker compose files you will find here https://github.com/weacast/weacast-app. I will update the doc accordingly.

However the error you have in the API is still strange, just like if a wrong version of the feathers-distributed dependency has been installed. I will have a look to the docker build.

**Comment by claustres** [comment]
In the meantime if you still have problems you can try to use the images with the `dev` tag and related docker compose files, which are current master and seems to work fine on my side.

**Comment by jemacchi** [comment]
hi @claustres, thanks for quick response. 
Cloning https://github.com/weacast/weacast-app.git and just running the `docker-compose up -d` command worked (with the **latest** tag). Thanks ! Great job! I will continue checking updates on project ! (as much as trying to catch up on coding side)
